micromic/api/urls.py
from django.urls import include, path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreateView, DetailsView, UserView, UserDetailsView, MaintenanceDetailsView, MaintenanceView
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'

urlpatterns = {
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dailyloglists/', CreateView.as_view(), name="create"),
    path('dailyloglists/<int:pk>/', DetailsView.as_view(), name="details"),
    path('maintenancelog/', MaintenanceView.as_view(), name="create"),
    path('maintenancelog/<int:pk>/', MaintenanceDetailsView.as_view(), name="details"),
    path('users/', UserView.as_view(), name="users"),
    path('users/<int:pk>/', UserDetailsView.as_view(), name="user_details"),
    path('get-token/', obtain_auth_token),

    #re_path(r'^dailyloglists/(?P<pk>[0-9]+)/$',
    #    DetailsView.as_view(), name="details"),
}

urlpatterns = format_suffix_patterns(urlpatterns)

micromic/frontend/urls.py
from django.urls import include, path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import dailylog_detail, dailylogs, homepage, maintenancelogs, maintenancelog_detail

app_name = 'frontend'

urlpatterns = {
    path('', homepage, name = 'homepage'),
    path('dailylogs/', dailylogs, name = 'dailylogs'),
    path('dailylogs/<int:dailylog_id>/', dailylog_detail, name='dailylog_detail'),
    path('maintenancelogs/', maintenancelogs, name = 'maintenancelogs'),
    path('maintenancelogs/<int:maintenancelog_id>/', maintenancelog_detail, name='maintenancelog_detail'),
}

urlpatterns = format_suffix_patterns(urlpatterns)

micromic/micromic/urls.py
"""micromic URL Configuration"""

from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls',namespace='api')),
    path('', include('frontend.urls',namespace='frontend'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

micromic/api/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
from .validators import validate_file_size

class DailyLogList(models.Model):
    """This class represents the DailyLogList model"""
    name = models.CharField(max_length = 255, blank = False, unique = True)
    owner = models.ForeignKey(
        'auth.User',
        related_name="dailyloglists",
        on_delete=models.CASCADE,
    )
    date_created = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[validate_file_size])

    def __str__(self):
        """Give me something I can read"""
        return "{}".format(self.name)


class MaintenanceList(models.Model):
    """This class represents the DailyLogList model"""
    owner = models.ForeignKey(
        'auth.User',
        related_name="maintenancelist",
        on_delete=models.CASCADE,
    )
    date_created = models.DateTimeField(auto_now_add = True, blank= False, unique=True)
    comment = models.CharField(max_length = 300, blank = False, unique = False)

    def __str__(self):
        """Give me something I can read"""
        return "{}".format(self.comment)


@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

micromic/frontend/models.py
from django.db import models

# Create your models here.

micromic/api/views.py
# api/views.py

from rest_framework import generics, permissions
from .permissions import IsOwner
from .serializers import DailyLogListSerializer, UserSerializer, MaintenanceListSerializer
from .models import DailyLogList, MaintenanceList
from django.contrib.auth.models import User

class CreateView(generics.ListCreateAPIView):
    """This class defines the create behavior of our rest api."""
    queryset = DailyLogList.objects.all()
    serializer_class = DailyLogListSerializer
    permission_classes = (
        permissions.IsAuthenticated,
        IsOwner
    )

    def perform_create(self, serializer):
        """Save the post data when creating a new bucketlist."""
        serializer.save(owner=self.request.user)


class DetailsView(generics.RetrieveUpdateDestroyAPIView):
    """This class handles the http GET, PUT and DELETE requests."""

    queryset = DailyLogList.objects.all()
    serializer_class = DailyLogListSerializer
    permission_classes = (
        permissions.IsAuthenticated,
        IsOwner
    )


class MaintenanceView(generics.ListCreateAPIView):
    """This class defines the create behavior of our rest api."""
    queryset = MaintenanceList.objects.all()
    serializer_class = MaintenanceListSerializer
    permission_classes = (
        permissions.IsAuthenticated,
        IsOwner
    )

    def perform_create(self, serializer):
        """Save the post data when creating a new bucketlist."""
        serializer.save(owner=self.request.user)


class MaintenanceDetailsView(generics.RetrieveUpdateDestroyAPIView):
    """This class handles the http GET, PUT and DELETE requests."""

    queryset = MaintenanceList.objects.all()
    serializer_class = MaintenanceListSerializer
    permission_classes = (
        permissions.IsAuthenticated,
        IsOwner
    )


class UserView(generics.ListAPIView):
    """View to list the user queryset."""
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetailsView(generics.RetrieveAPIView):
    """View to retrieve a user instance."""
    queryset = User.objects.all()
    serializer_class = UserSerializer

micromic/frontend/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from api.models import DailyLogList, MaintenanceList


def homepage(request, slug='index'):
    queryset = DailyLogList.objects.latest('date_created')
    context = {
        'slug': slug,
        'object' : queryset,
    }
    return render(request, "index.html", context)


def dailylogs(request, slug='dailylogs'):
    query = request.GET.get('datefilter')
    queryset = DailyLogList.objects.all()
    if (query):
        dates = query.split(' - ')
        queryset = queryset.filter(date_created__lte=dates[1], date_created__gte=dates[0])
    else:
        queryset = queryset[::-1]
    paginator = Paginator(queryset, 5)
    page = request.GET.get('page')
    queryset = paginator.get_page(page)
    context = {
        'slug': slug,
        "object_list" : queryset,
        'title': 'List',
    }
    return render(request, "dailylogs.html", context)


def dailylog_detail(request, dailylog_id):
    dailylog = get_object_or_404(DailyLogList, pk= dailylog_id)
    context = {
        'title': dailylog.name,
        'instance': dailylog,
    }
    return render(request, "dailylog_detial.html", context)


def maintenancelogs(request, slug="maintenancelogs"):
    query = request.GET.get('datefilter')
    queryset = MaintenanceList.objects.all()
    if (query):
        dates = query.split(' - ')
        queryset = queryset.filter(date_created__lte=dates[1], date_created__gte=dates[0])
    else:
        queryset = queryset[::-1]
    context = {
        'slug' : slug,
        'object_list' : queryset,
        'title': 'List',
    }
    return render(request, "maintenancelogs.html", context)


def maintenancelog_detail(request, maintenancelog_id):
    maintenancelog = get_object_or_404(MaintenanceList, pk=maintenancelog_id)
    context = {
        'title': maintenancelog.date_created,
        'instance': maintenancelog,
    }
    return render(request, "maintenancelog_detial.html", context)

micromic/templates/base.html
<!---DOCTYPE html --->

{% load static %}
<!---DOCTYPE html--->
<html lang = "en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title> {% block head_title %} MicroMit Journal{% endblock head_title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}"/>
    <style>
      {% block style}
      {% end block style}
    </style>
  </head>
  <body>

    {% block top-nav-wrapper %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MicroMic</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if slug == 'index' %}class="active"{% endif %}><a href="{% url 'frontend:homepage' %}">Home</a></li>
            <li {% if slug == 'dailylogs' %}class="active"{% endif %}><a href="{% url 'frontend:dailylogs' %}">Daily Logs</a></li>
            <li {% if slug == 'maintenancelogs' %}class="active"{% endif %}><a href="{% url 'frontend:maintenancelogs' %}">Maintenance Logs</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li {% if slug == 'login' %}class="active"{% endif %}><a href="{% url 'admin:index' %}"> Admin </a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% endblock %}

    {% block content %}{% endblock content %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/daterangepicker.min.js' %}"></script>

    <script type="text/javascript">

      $(document).ready(function(){
        $(".rMarkdown-QuickView").each(function(){
          var content = $(this).text().concat(" #air-temperature-termocouple")
          $(this).load(content);
        })
      })

      $(document).ready(function(){
        $(".rMarkdown").each(function()
        {var content = $(this).text()
          $(this).load(content);
        })
      })

      $(function() {
        $('input[name="datefilter"]').daterangepicker({
          minYear: 2018,
          autoUpdateInput: false,
          locale: {
            cancelLabel: 'Clear',
            format: 'YYYY-MM-DD'
          },
        });

        $('input[name="datefilter"]').on('apply.daterangepicker', function(ev, picker) {
          $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
          document.getElementById("dateSelect").submit();
        });

        $('input[name="datefilter"]').on('cancel.daterangepicker', function(ev, picker) {
          $(this).val('');
          document.getElementById("dateSelect").submit();
        });
      });


    </script>
  </body>
</html>

micromic/templates/dailylog_detial.html
{% extends "base.html" %}

{% load static %}

{% block head_title %} {{ title }} | {{ block.super }}  {% endblock head_title %}

{% block content %}
<hr>
<div class="row">
  <div class="col-md-6  col-md-offset-1">
    <div class = 'rMarkdown'>{% get_media_prefix %}{{ instance.upload }}</div>
  </div>
</div>
</hr>
{% endblock content %}

micromic/templates/dailylogs.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container fluid">
  <h2>Daily Logs</h2>

  {% include "dateSelect.html" %}

  {% for obj in object_list %}
  <div class="col-md-6  col-md-offset-1">
    <a href="{% url 'frontend:dailylog_detail' obj.id %}" class="btn btn-primary">{{obj.date_created}}</a>
  </div>
  <div class="col-md-8 col-md-offset-1">
    <div id='here' class='rMarkdown-QuickView'>{% get_media_prefix %}{{ obj.upload }}</div>
  </div>
  {% endfor %}
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-1">
      <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ object_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}">next</a>
                <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

micromic/templates/dateSelect.html
{% block searchBar %}
<nav class="navbar navbar-light bg-light">
<form class="form-inline" id="dateSelect" method='GET'>
  <input class="form-control mr-sm-2" type="text" name="datefilter" placeholder="Search">
</form>
</nav>
{% endblock searchBar %}

micromic/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Welcome to MicroMic</h1>
    <p>Home of the Daily logs and maintenance</p>
  </div>
</div>
<div class="container">
  <div class="col-md-8  col-md-offset-1">
    <div class = 'rMarkdown'>{% get_media_prefix %}{{ object.upload }}</div>
  </div>
</div>
<div class="jumbotron">
  <div class="container">
    <class class="row">
      <class class="col-md-6">
        <h2>About</h2>
      </class>
      <class class="col-md-6">
        <h2>Contact</h2>
      </class>
    </class>
  </div>
</div>
{% endblock content %}

micromic/templates/maintenancelog_detial.html
{% extends "base.html" %}

{% block content %}

<h1> {{ title }} </h1>
{% load static %}

{{ instance.comment}}<br/>
{{ instance.owner }}<br/>

{% endblock content %}

micromic/templates/maintenancelogs.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-1">
      <h2>Maintenance Logs</h2>
      {% include "dateSelect.html" %}
    </div>
  </div>
  {% for obj in object_list %}
  <hr>
  <div class="row">
    <div class="col-md-6  col-md-offset-1">
      <h3><a href="{% url 'frontend:maintenancelog_detail' obj.id %}">{{ obj.date_created }}</a></h3>
    </div>
    <div class="col-md-8 col-md-offset-1">
        <ul class="b">{{ obj.comment}}</ul>
    </div>
  </div>
</hr>
  {% endfor %}
</div>
{% endblock content %}